### ISSUE TITLE
Self-host all images

### ISSUE THREAD

**Issue by lamby** [freenode/freenodejobs#19]
We should self-host all images instead of linking them cross-domain in case they break.

eg. https://github.com/freenode/freenodejobs/commit/8bea131d5649a0019bf099f493ce43e7bed4ef0c/#diff-9b7c06180861bd11cd8d6f792ebd6da2R43

**Comment by christeld** [comment]
+1 from me -- feel free to grab the freenode one from https://assets.freenode.net and update.

**Comment by svbeon** [comment]
Yeah I should actually state that even clearer on `assets.`, it's not a cdn, just a place to go to to grab raw/uncompressed versions of files to use in other things :)
