### ISSUE TITLE
Validation on Create Profile form

### ISSUE THREAD

**Issue by fndax** [freenode/freenodejobs#26]
The validation hints on the Create Profile page are a bit off.

Steps to reproduce:

1. Go to https://jobs.freenode.net/profile to create your org's profile
2. Click "Create profile" without entering any data, note that Name and URL boxes get red outlines and errors but Image doesn't (so it looks like Image is optional?)
3. Enter info in the Name and URL boxes but don't upload an image
4. Click "Create profile" again
5. Now it complains about missing an image

Additionally, it might also be useful to add text to the Create Profile page saying that all three fields are required, and any other limitations (length restrictions on Name, which appear to be 255 chars. image file size restrictions that I assume exist, etc.)

**Comment by fndax** [comment]
> image file size restrictions that I assume exist

I attempted to upload https://upload.wikimedia.org/wikipedia/commons/c/cb/GLIMPSE-MIPSGAL_Milky_Way_12.jpg [7.5 MB] as my profile picture and got an nginx "413 Request Entity Too Large" error, so yes, they exist.

**Comment by fndax** [comment]
> length restrictions on Name, which appear to be 255 chars

And the one on URL appears to be 200 characters.

Currently it silently truncates both Name and URL if they're over; I'm not sure if that's the best behaviour or if it should error and make the user fix it instead.

**Comment by lamby** [comment]
(I've split this issue into #30, #31 and #32 so they can be tracked separately. Closing this one.)

**Comment by fndax** [comment]
Thanks, wasn't sure how much Issues email you wanted. Will split things up more in future :)

**Comment by lamby** [comment]
@fndax Appreciated! Always easer to merge tickets than to split them — both technically and cognitively —  so always err on the side on filing more :)
