### ISSUE TITLE
Add job type for FOSS volunteers

### ISSUE THREAD

**Issue by fndax** [freenode/freenodejobs#28]
Christel's draft blog post currently says:

> FOSS or other peer-directed project on the hunt for volunteers?
> Why not add a post on the jobs.freenode.net site to see if you may be able to attract some contributors from the wider freenode and FOSS communities?

The available job types currently are "Full-time", "Part-time", and "Contract". None of them really fit as-time-permits unpaid volunteering, so we might want a fourth option named "Volunteer" or something (and I imagine people looking for actual paid work would appreciate having volunteering opportunities as a separate type so they can filter them out).

**Comment by lamby** [comment]
> so we might want a fourth option

Assigning @christeld for clarification.

**Comment by christeld** [comment]
That would be handy if it is not too much hassle! :)
