### ISSUE TITLE
Image field should not appear to be valid when it is required on profile form

### ISSUE THREAD

**Issue by lamby** [freenode/freenodejobs#31]
Splitting from #26, @fndax wrote:

> red outlines and errors but Image doesn't (so it looks like Image is optional?)

**Comment by lamby** [comment]
@fndax I can't reproduce this either. So, we also set some front-end validation using the HTML5 `required` tag (for a better user experience) but even when you workaround this and one simply presses *Create profile* I get:

![](https://i.imgur.com/Pna1ncb.jpg)

Any ideas on how I can reproduce what you are seeing?

**Comment by fndax** [comment]
Odd. This is what I get on Firefox 60 when I create a new account, go to the Create Profile screen, and click the Create profile button:

![screenshot_20180604_072835](https://user-images.githubusercontent.com/23448388/40923157-e4d99a28-67c8-11e8-9e81-c4bd8fb18880.png)

**Comment by lamby** [comment]
Now that is very odd. Whilst I could probably understand that Firefox did not support rendering of a red border around the image field (file upload fields are treated differently in browsers due to security issues after all) what I don't understand right now is why we are not rendering the "Your must specify an image." That is sent by the server, suggesting that we are not detecting the lack of image properly...

**Comment by lamby** [comment]
![](https://i.imgur.com/OKVUfjs.png)

Hm, I can't even reproduce this (FF 52.8.0 here..)

**Comment by lamby** [comment]
I think f13717c should fix this, but I am curious still why this occurs... :)
