### ISSUE TITLE
Should not silently truncate Name and URL on profile form

### ISSUE THREAD

**Issue by lamby** [freenode/freenodejobs#32]
Splitting from #26, @fndax wrote:

> Currently it silently truncates both Name and URL if they're over; I'm not sure if that's the best behaviour or if it should error and make the user fix it instead.

**Comment by lamby** [comment]
@fndax I can't reproduce this. So, first the "Name" field has the client-side validation indicator `maxlength=255` so this is unlikely to even occur in the "real world." Furthermore, even if you override that, the server-side validation kicks in:

![](https://i.imgur.com/3q5gcCa.jpg)

Same applies for the URL:

![](https://i.imgur.com/cb7SgBh.jpg)

Can you provide more detailson what you did so I can reproduce this? Please assign back when done. :)

**Comment by fndax** [comment]
Oh, duh, it was truncating it before I submitted it (because of the maxlength=255) and I didn't notice. Yeah, that behaviour should be fine, it'd be fairly obvious if you weren't copy/pasting it like I was.

**Comment by lamby** [comment]
No worries; closing issue to match. :)
